version: "3"

services:
  phoenix_blogs_web:
    build: .
    container_name: phoenix_blogs_web
    command: /app/scripts/entry_point.sh
    volumes:
      - ./src:/app
    ports:
      - 4000:4000
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: phoenix_blogs
      PGHOST: phoenix_blogs_db
      PGPORT: 5432
    depends_on:
      - phoenix_blogs_db
  phoenix_blogs_db:
    image: postgres:14.2
    container_name: phoenix_blogs_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes:
      - ./docker-volumes/postgres-data:/var/lib/postgresql/data